# https://docs.travis-ci.com/user/environment-variables/
language: csharp
dotnet: 2.1.302

branches:
  only:
  - master

services:
  - docker
  - postgresql

addons:
  postgresql: "9.5"

# Symbolic link is a fix for Ubuntu using "nodejs" not "node"
install:
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - cd src/Letmein.Web/wwwroot
  - npm config set registry http://registry.npmjs.org/
  - npm install
  - cd ../../../

before_script:
  - psql -c 'create database letmein;' -U postgres

script:
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run-master.sh; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run-pullrequest.sh; fi'
