# fly.toml app configuration file generated for letmein on 2025-10-28T00:05:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'letmein'
primary_region = "lhr"

[http_service]
auto_start_machines = true
auto_stop_machines = "suspend"
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256mb"
