FROM mcr.microsoft.com/dotnet/aspnet:8.0
MAINTAINER Chris Small

RUN mkdir /app
COPY ./bin/Release/netcoreapp8.0/linux-x64/publish /app
WORKDIR /app

RUN mkdir /app/storage
RUN chmod 777 /app/storage
#RUN apt-get update
#RUN apt-get install curl -y

ENTRYPOINT ["dotnet", "/app/Letmein.Web.dll"]

# ASP.NET Core: make sure views use the production versions
ENV ASPNETCORE_ENVIRONMENT="Production"

# ASP.NET Core: Kestrel should listen on all IPs
#ENV ASPNETCORE_URLS="http://0.0.0.0:5000,https://0.0.0.0:5001"
#ENV ASPNETCORE_HTTP_PORTS=5000

# The storage type for pastes.
# Possible values:  "FileSystem", "Postgres", "S3", "GoogleCloud", "AzureBlobs"
ENV REPOSITORY_TYPE="FileSystem"

# Postgres database connection string
ENV POSTGRES_CONNECTIONSTRING=""

# A comma-seperated list of minutes that pastes expire after.
ENV EXPIRY_TIMES="720"

# Number of seconds to sleep inbetween checking for expired pastes
ENV CLEANUP_SLEEPTIME="300"

# Short url ID type. 
# Possible values: default (random-with-pronounceable), pronounceable, short-pronounceable, short-mixedcase, shortcode
ENV ID_TYPE="default"

# Various UI customisations
ENV PAGE_TITLE="letmein.io"
ENV HEADER_TEXT="letmein.io"
ENV HEADER_SUBTEXT="note encryption service"
ENV FOOTER_TEXT="<a href="https://github.com/yetanotherchris/letmein">Github source</a>&nbsp;|&nbsp;<a href="/FAQ">FAQ</a>"
