apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: letmein-ingress
spec:
  # remove defaultBackend if your k8 cluster is serving multiple sites
  defaultBackend:
    service:
      name: letmein-website
      port:
        number: 5000
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: letmein-website
            port:
              number: 5000